# Generated by Django 6.1.2 on 2026-10-06 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100, verbose_name='región')),
                ('comuna', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('category', models.CharField(max_length=80, verbose_name='categoría')),
                ('unit_cost', models.PositiveBigIntegerField(verbose_name='costo unitario (CLP)')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='precio unitario (CLP)')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('region', models.CharField(max_length=100, verbose_name='región')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('shipped', 'Enviada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('destination_region', models.CharField(max_length=100, verbose_name='región de destino')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
            options={
                'verbose_name': 'Orden de venta',
                'verbose_name_plural': 'Órdenes de venta',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=60, unique=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='precio unitario (CLP)')),
                ('unit_cost', models.PositiveBigIntegerField(verbose_name='costo unitario (CLP)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Ítem de orden',
                'verbose_name_plural': 'Ítems de orden',
            },
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('reason', models.CharField(max_length=50, verbose_name='motivo')),
                ('refund_amount', models.PositiveBigIntegerField(verbose_name='monto de reembolso (CLP)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orderitem')),
            ],
            options={
                'verbose_name': 'Devolución de producto',
                'verbose_name_plural': 'Devoluciones de productos',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='product_return_quantity_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('promised_at', models.DateTimeField(verbose_name='fecha prometida')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carrier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'constraints': [models.UniqueConstraint(fields=('order', 'warehouse'), name='shipment_unique_order_warehouse'), models.CheckConstraint(condition=models.Q(('shipped_at__isnull', True), ('delivered_at__isnull', True), ('delivered_at__gte', models.F('shipped_at')), _connector='OR'), name='shipment_delivered_after_shipped')],
            },
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_gt_0'),
        ),
    ]
